apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-simple-prod
spec:
  strategy: production
  allInOne:
    image: jaegertracing/all-in-one:latest
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    storage:
      type: memory
      options:
        memory:
          max-traces: 100000
