apiVersion: apps/v1
kind: Deployment
metadata:
  name: envtest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: envtest
  template:
    metadata:
      labels:
        name: envtest
    spec:
      containers:
      - name: envtest
        image: zzzloy777/k8-example-envs-js:latest
        ports:
        - containerPort: 3000
        env:
        - name: LANGUAGE
          valueFrom:
            configMapKeyRef:
              name: language
              key: LANGUAGE
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: apikey
              key: API_KEY
