version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:9.4.7
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_USERS_DEFAULT_THEME=light
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/nodejs-dashboard.json
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 9000:3000
    depends_on:
      - prometheus
