apiVersion: apps/v1
kind: Deployment
metadata:
  name: envtest-file
spec:
  replicas: 1
  selector:
    matchLabels:
      name: envtest-file
  template:
    metadata:
      labels:
        name: envtest-file
    spec:
      containers:
      - name: envtest-file
        image: zzzloy777/k8-example-env-files-js:latest
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: my-config
            mountPath: /app/config
          - name: my-secret
            mountPath: /app/secret
      volumes:
        - name: my-config
          configMap:
            name: my-config
        - name: my-secret
          secret:
            secretName: my-secret
