grafana:
  grafana.ini:
    unified_alerting:
      enabled: true
    alerting:
      enabled: false
    smtp:
      enabled: true
      host: mail.do-it.co:26
      from_address: "e.nguita@do-it.co"
  smtp:
    existingSecret: grafana-smtp-credentials
  adminPassword: "111111"

